const GMAIL_LABELS = {

    LOCALIZA: "LOCALIZA_LAVAGEM",

    IMPORTADO: "LF_IMPORTADO",

    AGUARDANDO: "LF_AGUARDANDO",

    EM_LAVAGEM: "LF_EM_LAVAGEM",

    FINALIZADO: "LF_FINALIZADO",

    ERRO_IMPORTACAO: "LF_ERRO_IMPORTACAO"

};

export default GMAIL_LABELS;